### ISSUE TITLE
live preview error edge code edge code

### ISSUE THREAD

**Issue by Max-Enrik** [edge-code/edge-code#1]
live preview error what is it?
How can I do for this issue?

Thanks.
Max

**Comment by bchintx** [comment]
The Live Preview error results from a change in Chrome 34.  This will be fixed in our next release.

**Comment by Max-Enrik** [comment]
Hello Bryan,

Thanks for your answer.
Same effects when I have been reinstalling Edge Code CC.
Perhaps I don't understanding...?

Thanks

**Comment by bchintx** [comment]
Sorry for the confusion.  I meant to say that this will be fixed in an upcoming release of Edge Code.
